[package]
name = "hla-errors"
version = "1.6.3"
edition = "2021"

[dependencies]
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0.63"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
