[package]
name = "hl-advanced"
version = "1.6.2"
edition = "2021"

[dependencies]
logos = "0.13"
chumsky = "0.9"
indextree = "4.6"
miette = { version = "7.2", features = ["fancy"] }
thiserror = "1.0"
clap = { version = "4.5", features = ["derive"] }

