[package]
name = "hl-plsa"
version = "1.7.1"
edition = "2021"

[dependencies]
pest = "2.7.6"
pest_derive = "2.7.6"
serde = { version = "1.0", features = ["derive"] }
miette = { version = "5.10", features = ["fancy"] }
thiserror = "1.0"
colored = "2.0"
dirs = "5.0"
