[package]
name    = "hl-runtime"
version = "1.7.1"
edition = "2021"

[dependencies]
serde    = { version = "1.0", features = ["derive"] }
colored  = "2.0"
sha2     = "0.10"
hex      = "0.4"
dirs     = "5.0"
bincode  = "1.3"
dynasmrt = "2.0"
hl-plsa  = { path = "../hl-plsa" }
