[package]
name    = "hl"
version = "1.7.0"
edition = "2021"

[[bin]]
name = "hl"
path = "src/main.rs"

[dependencies]
hl-compiler = { path = "../hl-compiler" }
hl-runtime  = { path = "../hl-runtime" }
lexopt      = "0.3"
owo-colors  = "4.0"
