[package]
name = "hl-compiler"
version = "1.6.2"
edition = "2021"

[dependencies]
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
subprocess = "0.2.9"
dirs = "5.0"
